### ISSUE TITLE
Move to ember-polyfills?

### ISSUE THREAD

**Issue by chancancode** [ember-polyfills/ember-functions-as-helper-polyfill#120]
Hi @NullVoxPopuli, are you interested in moving this to the [official polyfills](https://github.com/ember-polyfills) org? Is this feature-complete in your opinion and something that we should recommend to Ember users wanting this feature?

**Comment by NullVoxPopuli** [comment]
I think once I land https://github.com/NullVoxPopuli/ember-functions-as-helper-polyfill/issues/121
it'll be feature-complete, and I'll transfer it over :partying_face:
